# Generated by Django 5.1.1 on 2024-09-30 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('idagent', models.AutoField(primary_key=True, serialize=False)),
                ('nomagent', models.CharField(max_length=255)),
                ('prenomagent', models.CharField(max_length=255)),
                ('fonction', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idclient', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('idprospect', models.AutoField(primary_key=True, serialize=False)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=50)),
                ('referant', models.CharField(max_length=255)),
                ('contact_referant', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('idincident', models.AutoField(primary_key=True, serialize=False)),
                ('site', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('responsabilite', models.CharField(max_length=255)),
                ('intervenant', models.CharField(max_length=255)),
                ('idclient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkapp0.client')),
            ],
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('iddossier', models.AutoField(primary_key=True, serialize=False)),
                ('titre_projet', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
                ('statut', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('courrierreference', models.CharField(max_length=255)),
                ('date_depot', models.DateField()),
                ('date_relance', models.DateField()),
                ('idagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkapp0.agent')),
                ('idprospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkapp0.prospect')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('numrecharge', models.AutoField(primary_key=True, serialize=False)),
                ('numerosim', models.CharField(max_length=20)),
                ('volume', models.CharField(max_length=50)),
                ('site', models.CharField(max_length=255)),
                ('dateexpiration', models.DateField()),
                ('idprospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkapp0.prospect')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='idprospect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkapp0.prospect'),
        ),
    ]
