# Generated by Django 5.1.1 on 2024-09-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkapp0', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='date',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
