# Generated by Django 5.1.1 on 2024-09-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkapp0', '0002_prospect_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
