# Generated by Django 4.2 on 2024-10-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkapp0', '0003_alter_prospect_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='service',
            field=models.CharField(choices=[('interconnexion', 'Interconnexion'), ('maintenance', 'Maintenance'), ('reseau', 'Réseau'), ('developpement', 'Développement'), ('livraison', 'Livraison'), ('divers', 'Divers')], max_length=255),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='statut',
            field=models.CharField(choices=[('rdv1_a_fixer', 'RDV1 à fixer'), ('rdv1_pris', 'RDV1 Pris'), ('devis_remis_negociation', 'Devis Remis-Négo'), ('signe_a_valider', 'Signé-A valider'), ('signe_valide', 'Signé-Validé'), ('signe_annule', 'Signé-Annulé'), ('sans_suite_abandonne', 'Sans suite-Abandonné'), ('perdu', 'Perdu'), ('en_attente', 'En attente'), ('termine', 'Terminé')], max_length=100),
        ),
    ]
