# Generated by Django 5.1.1 on 2024-10-07 16:01

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkapp0', '0004_alter_dossier_service_alter_dossier_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='intervenant',
        ),
        migrations.AddField(
            model_name='incident',
            name='dateenregistrement',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='dateincident',
            field=models.DateField(default=datetime.datetime(2024, 10, 7, 16, 0, 32, 838580, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='heureincident',
            field=models.TimeField(default=datetime.time(16, 1, 6, 918536)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('idintervention', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('equipe', models.CharField(max_length=255)),
                ('idincident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkapp0.incident')),
            ],
        ),
    ]
