# Generated by Django 5.1.1 on 2024-10-10 19:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkapp0', '0005_remove_incident_intervenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='daterecharge',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
