# Generated by Django 5.1.1 on 2024-10-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkapp0', '0006_data_daterecharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('depasse', 'Dépassé')], default='en_cours', max_length=10),
        ),
    ]
